"""Redistribute generated resumes (all .txt) into 8 txt / 8 docx / 8 pdf / 8 pptx.

Resumes 01-08 stay .txt, 09-16 -> .docx, 17-24 -> .pdf, 25-32 -> .pptx.
Requires all 32 resumes already generated by scripts/generate_data.py.
"""
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from backend import fs_tools

RESUME_DIR = "data/resumes"

RANGES = [
    (1, 8, ".txt"),
    (9, 16, ".docx"),
    (17, 24, ".pdf"),
    (25, 32, ".pptx"),
]


def main():
    files = sorted(fs_tools.list_files(RESUME_DIR, extension=".txt"), key=lambda f: f["name"])
    by_index = {}
    for entry in files:
        try:
            idx = int(entry["name"].split("_")[1])
        except (IndexError, ValueError):
            continue
        by_index[idx] = entry["name"]

    for start, end, target_ext in RANGES:
        for idx in range(start, end + 1):
            src_name = by_index.get(idx)
            if not src_name:
                print(f"  missing resume {idx:02d}, skip")
                continue
            if target_ext == ".txt":
                print(f"  {src_name}: keep as .txt")
                continue

            src_path = os.path.join(RESUME_DIR, src_name)
            read_result = fs_tools.read_file(src_path)
            if not read_result["success"]:
                print(f"  {src_name}: read failed: {read_result['error']}")
                continue

            dst_name = os.path.splitext(src_name)[0] + target_ext
            dst_path = os.path.join(RESUME_DIR, dst_name)
            write_result = fs_tools.write_file(dst_path, read_result["content"])
            if not write_result["success"]:
                print(f"  {src_name}: write {target_ext} failed: {write_result['error']}")
                continue

            os.remove(src_path)
            print(f"  {src_name} -> {dst_name}")

    print("\nDone. Final format counts:")
    for ext in (".txt", ".docx", ".pdf", ".pptx"):
        n = len(fs_tools.list_files(RESUME_DIR, extension=ext))
        print(f"  {ext}: {n}")


if __name__ == "__main__":
    main()
